My first interaction with python exceptions
